(cl:defpackage mte411_services-srv
  (:use )
  (:export
   "ENCODER"
   "<ENCODER-REQUEST>"
   "ENCODER-REQUEST"
   "<ENCODER-RESPONSE>"
   "ENCODER-RESPONSE"
   "RANDOM"
   "<RANDOM-REQUEST>"
   "RANDOM-REQUEST"
   "<RANDOM-RESPONSE>"
   "RANDOM-RESPONSE"
   "VOLTAGETOTEMP"
   "<VOLTAGETOTEMP-REQUEST>"
   "VOLTAGETOTEMP-REQUEST"
   "<VOLTAGETOTEMP-RESPONSE>"
   "VOLTAGETOTEMP-RESPONSE"
  ))

