(cl:defpackage mte411_services-srv
  (:use )
  (:export
   "RANDOM"
   "<RANDOM-REQUEST>"
   "RANDOM-REQUEST"
   "<RANDOM-RESPONSE>"
   "RANDOM-RESPONSE"
   "VOLTAGETOTEMP"
   "<VOLTAGETOTEMP-REQUEST>"
   "VOLTAGETOTEMP-REQUEST"
   "<VOLTAGETOTEMP-RESPONSE>"
   "VOLTAGETOTEMP-RESPONSE"
  ))

