// Generated by gencpp from file mte411_services/EncoderRequest.msg
// DO NOT EDIT!


#ifndef MTE411_SERVICES_MESSAGE_ENCODERREQUEST_H
#define MTE411_SERVICES_MESSAGE_ENCODERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8.h>

namespace mte411_services
{
template <class ContainerAllocator>
struct EncoderRequest_
{
  typedef EncoderRequest_<ContainerAllocator> Type;

  EncoderRequest_()
    : pulse()  {
    }
  EncoderRequest_(const ContainerAllocator& _alloc)
    : pulse(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8_<ContainerAllocator>  _pulse_type;
  _pulse_type pulse;





  typedef boost::shared_ptr< ::mte411_services::EncoderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mte411_services::EncoderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderRequest_

typedef ::mte411_services::EncoderRequest_<std::allocator<void> > EncoderRequest;

typedef boost::shared_ptr< ::mte411_services::EncoderRequest > EncoderRequestPtr;
typedef boost::shared_ptr< ::mte411_services::EncoderRequest const> EncoderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mte411_services::EncoderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mte411_services::EncoderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mte411_services::EncoderRequest_<ContainerAllocator1> & lhs, const ::mte411_services::EncoderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pulse == rhs.pulse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mte411_services::EncoderRequest_<ContainerAllocator1> & lhs, const ::mte411_services::EncoderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mte411_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mte411_services::EncoderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mte411_services::EncoderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mte411_services::EncoderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mte411_services::EncoderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mte411_services::EncoderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mte411_services::EncoderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mte411_services::EncoderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5a7ffe2a5c0abd253bcf837aec25bbe";
  }

  static const char* value(const ::mte411_services::EncoderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5a7ffe2a5c0abd2ULL;
  static const uint64_t static_value2 = 0x53bcf837aec25bbeULL;
};

template<class ContainerAllocator>
struct DataType< ::mte411_services::EncoderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mte411_services/EncoderRequest";
  }

  static const char* value(const ::mte411_services::EncoderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mte411_services::EncoderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8 pulse\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
;
  }

  static const char* value(const ::mte411_services::EncoderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mte411_services::EncoderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pulse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mte411_services::EncoderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mte411_services::EncoderRequest_<ContainerAllocator>& v)
  {
    s << indent << "pulse: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.pulse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MTE411_SERVICES_MESSAGE_ENCODERREQUEST_H
