// Generated by gencpp from file mte411_services/Encoder.msg
// DO NOT EDIT!


#ifndef MTE411_SERVICES_MESSAGE_ENCODER_H
#define MTE411_SERVICES_MESSAGE_ENCODER_H

#include <ros/service_traits.h>


#include <mte411_services/EncoderRequest.h>
#include <mte411_services/EncoderResponse.h>


namespace mte411_services
{

struct Encoder
{

typedef EncoderRequest Request;
typedef EncoderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Encoder
} // namespace mte411_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mte411_services::Encoder > {
  static const char* value()
  {
    return "11323230cb3de4d996e64a4ff33ac375";
  }

  static const char* value(const ::mte411_services::Encoder&) { return value(); }
};

template<>
struct DataType< ::mte411_services::Encoder > {
  static const char* value()
  {
    return "mte411_services/Encoder";
  }

  static const char* value(const ::mte411_services::Encoder&) { return value(); }
};


// service_traits::MD5Sum< ::mte411_services::EncoderRequest> should match
// service_traits::MD5Sum< ::mte411_services::Encoder >
template<>
struct MD5Sum< ::mte411_services::EncoderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mte411_services::Encoder >::value();
  }
  static const char* value(const ::mte411_services::EncoderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mte411_services::EncoderRequest> should match
// service_traits::DataType< ::mte411_services::Encoder >
template<>
struct DataType< ::mte411_services::EncoderRequest>
{
  static const char* value()
  {
    return DataType< ::mte411_services::Encoder >::value();
  }
  static const char* value(const ::mte411_services::EncoderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mte411_services::EncoderResponse> should match
// service_traits::MD5Sum< ::mte411_services::Encoder >
template<>
struct MD5Sum< ::mte411_services::EncoderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mte411_services::Encoder >::value();
  }
  static const char* value(const ::mte411_services::EncoderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mte411_services::EncoderResponse> should match
// service_traits::DataType< ::mte411_services::Encoder >
template<>
struct DataType< ::mte411_services::EncoderResponse>
{
  static const char* value()
  {
    return DataType< ::mte411_services::Encoder >::value();
  }
  static const char* value(const ::mte411_services::EncoderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MTE411_SERVICES_MESSAGE_ENCODER_H
