// Generated by gencpp from file mte411_services/EncoderResponse.msg
// DO NOT EDIT!


#ifndef MTE411_SERVICES_MESSAGE_ENCODERRESPONSE_H
#define MTE411_SERVICES_MESSAGE_ENCODERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace mte411_services
{
template <class ContainerAllocator>
struct EncoderResponse_
{
  typedef EncoderResponse_<ContainerAllocator> Type;

  EncoderResponse_()
    : RPM()  {
    }
  EncoderResponse_(const ContainerAllocator& _alloc)
    : RPM(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _RPM_type;
  _RPM_type RPM;





  typedef boost::shared_ptr< ::mte411_services::EncoderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mte411_services::EncoderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderResponse_

typedef ::mte411_services::EncoderResponse_<std::allocator<void> > EncoderResponse;

typedef boost::shared_ptr< ::mte411_services::EncoderResponse > EncoderResponsePtr;
typedef boost::shared_ptr< ::mte411_services::EncoderResponse const> EncoderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mte411_services::EncoderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mte411_services::EncoderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mte411_services::EncoderResponse_<ContainerAllocator1> & lhs, const ::mte411_services::EncoderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.RPM == rhs.RPM;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mte411_services::EncoderResponse_<ContainerAllocator1> & lhs, const ::mte411_services::EncoderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mte411_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mte411_services::EncoderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mte411_services::EncoderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mte411_services::EncoderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mte411_services::EncoderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mte411_services::EncoderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mte411_services::EncoderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mte411_services::EncoderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8454e229bf7eebfb11877ce1b6826938";
  }

  static const char* value(const ::mte411_services::EncoderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8454e229bf7eebfbULL;
  static const uint64_t static_value2 = 0x11877ce1b6826938ULL;
};

template<class ContainerAllocator>
struct DataType< ::mte411_services::EncoderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mte411_services/EncoderResponse";
  }

  static const char* value(const ::mte411_services::EncoderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mte411_services::EncoderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 RPM\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::mte411_services::EncoderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mte411_services::EncoderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RPM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mte411_services::EncoderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mte411_services::EncoderResponse_<ContainerAllocator>& v)
  {
    s << indent << "RPM: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.RPM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MTE411_SERVICES_MESSAGE_ENCODERRESPONSE_H
