// Generated by gencpp from file mte411_services/RandomRequest.msg
// DO NOT EDIT!


#ifndef MTE411_SERVICES_MESSAGE_RANDOMREQUEST_H
#define MTE411_SERVICES_MESSAGE_RANDOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace mte411_services
{
template <class ContainerAllocator>
struct RandomRequest_
{
  typedef RandomRequest_<ContainerAllocator> Type;

  RandomRequest_()
    : Entery()  {
    }
  RandomRequest_(const ContainerAllocator& _alloc)
    : Entery(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _Entery_type;
  _Entery_type Entery;





  typedef boost::shared_ptr< ::mte411_services::RandomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mte411_services::RandomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RandomRequest_

typedef ::mte411_services::RandomRequest_<std::allocator<void> > RandomRequest;

typedef boost::shared_ptr< ::mte411_services::RandomRequest > RandomRequestPtr;
typedef boost::shared_ptr< ::mte411_services::RandomRequest const> RandomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mte411_services::RandomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mte411_services::RandomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mte411_services::RandomRequest_<ContainerAllocator1> & lhs, const ::mte411_services::RandomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Entery == rhs.Entery;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mte411_services::RandomRequest_<ContainerAllocator1> & lhs, const ::mte411_services::RandomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mte411_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mte411_services::RandomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mte411_services::RandomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mte411_services::RandomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mte411_services::RandomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mte411_services::RandomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mte411_services::RandomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mte411_services::RandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d7f55175650d81b01eafca1e617e8e6";
  }

  static const char* value(const ::mte411_services::RandomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d7f55175650d81bULL;
  static const uint64_t static_value2 = 0x01eafca1e617e8e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::mte411_services::RandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mte411_services/RandomRequest";
  }

  static const char* value(const ::mte411_services::RandomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mte411_services::RandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool Entery\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::mte411_services::RandomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mte411_services::RandomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Entery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RandomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mte411_services::RandomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mte411_services::RandomRequest_<ContainerAllocator>& v)
  {
    s << indent << "Entery: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.Entery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MTE411_SERVICES_MESSAGE_RANDOMREQUEST_H
