// Generated by gencpp from file mte411_services/Random.msg
// DO NOT EDIT!


#ifndef MTE411_SERVICES_MESSAGE_RANDOM_H
#define MTE411_SERVICES_MESSAGE_RANDOM_H

#include <ros/service_traits.h>


#include <mte411_services/RandomRequest.h>
#include <mte411_services/RandomResponse.h>


namespace mte411_services
{

struct Random
{

typedef RandomRequest Request;
typedef RandomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Random
} // namespace mte411_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mte411_services::Random > {
  static const char* value()
  {
    return "2880ddbf81389eed9201b6ff083b33fa";
  }

  static const char* value(const ::mte411_services::Random&) { return value(); }
};

template<>
struct DataType< ::mte411_services::Random > {
  static const char* value()
  {
    return "mte411_services/Random";
  }

  static const char* value(const ::mte411_services::Random&) { return value(); }
};


// service_traits::MD5Sum< ::mte411_services::RandomRequest> should match
// service_traits::MD5Sum< ::mte411_services::Random >
template<>
struct MD5Sum< ::mte411_services::RandomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mte411_services::Random >::value();
  }
  static const char* value(const ::mte411_services::RandomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mte411_services::RandomRequest> should match
// service_traits::DataType< ::mte411_services::Random >
template<>
struct DataType< ::mte411_services::RandomRequest>
{
  static const char* value()
  {
    return DataType< ::mte411_services::Random >::value();
  }
  static const char* value(const ::mte411_services::RandomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mte411_services::RandomResponse> should match
// service_traits::MD5Sum< ::mte411_services::Random >
template<>
struct MD5Sum< ::mte411_services::RandomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mte411_services::Random >::value();
  }
  static const char* value(const ::mte411_services::RandomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mte411_services::RandomResponse> should match
// service_traits::DataType< ::mte411_services::Random >
template<>
struct DataType< ::mte411_services::RandomResponse>
{
  static const char* value()
  {
    return DataType< ::mte411_services::Random >::value();
  }
  static const char* value(const ::mte411_services::RandomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MTE411_SERVICES_MESSAGE_RANDOM_H
