// Generated by gencpp from file mte411_services/VoltageToTemp.msg
// DO NOT EDIT!


#ifndef MTE411_SERVICES_MESSAGE_VOLTAGETOTEMP_H
#define MTE411_SERVICES_MESSAGE_VOLTAGETOTEMP_H

#include <ros/service_traits.h>


#include <mte411_services/VoltageToTempRequest.h>
#include <mte411_services/VoltageToTempResponse.h>


namespace mte411_services
{

struct VoltageToTemp
{

typedef VoltageToTempRequest Request;
typedef VoltageToTempResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoltageToTemp
} // namespace mte411_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mte411_services::VoltageToTemp > {
  static const char* value()
  {
    return "c1cf9257061f040a91bd584c238b489a";
  }

  static const char* value(const ::mte411_services::VoltageToTemp&) { return value(); }
};

template<>
struct DataType< ::mte411_services::VoltageToTemp > {
  static const char* value()
  {
    return "mte411_services/VoltageToTemp";
  }

  static const char* value(const ::mte411_services::VoltageToTemp&) { return value(); }
};


// service_traits::MD5Sum< ::mte411_services::VoltageToTempRequest> should match
// service_traits::MD5Sum< ::mte411_services::VoltageToTemp >
template<>
struct MD5Sum< ::mte411_services::VoltageToTempRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mte411_services::VoltageToTemp >::value();
  }
  static const char* value(const ::mte411_services::VoltageToTempRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mte411_services::VoltageToTempRequest> should match
// service_traits::DataType< ::mte411_services::VoltageToTemp >
template<>
struct DataType< ::mte411_services::VoltageToTempRequest>
{
  static const char* value()
  {
    return DataType< ::mte411_services::VoltageToTemp >::value();
  }
  static const char* value(const ::mte411_services::VoltageToTempRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mte411_services::VoltageToTempResponse> should match
// service_traits::MD5Sum< ::mte411_services::VoltageToTemp >
template<>
struct MD5Sum< ::mte411_services::VoltageToTempResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mte411_services::VoltageToTemp >::value();
  }
  static const char* value(const ::mte411_services::VoltageToTempResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mte411_services::VoltageToTempResponse> should match
// service_traits::DataType< ::mte411_services::VoltageToTemp >
template<>
struct DataType< ::mte411_services::VoltageToTempResponse>
{
  static const char* value()
  {
    return DataType< ::mte411_services::VoltageToTemp >::value();
  }
  static const char* value(const ::mte411_services::VoltageToTempResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MTE411_SERVICES_MESSAGE_VOLTAGETOTEMP_H
